// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    Page: typeof import('./src/components/Page.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    SidebarNavigation: typeof import('./src/components/Sidebar/Navigation.vue')['default']
    SidebarNavigationItem: typeof import('./src/components/Sidebar/Navigation/Item.vue')['default']
  }

}
